#pragma once
#include <map>
#include <string>
#include <vector>
std::map<int, int> bidMap{

};
std::set<int> freelots;


std::map<int, std::vector<std::string>> dataMap = {
    {15132, {"Warrior's Calligae", "warriors_calligae", "war", "WAR Feet"}},
    {15118, {"Melee Hose", "melee_hose", "mnk", "MNK Legs"}},
    {15074, {"Cleric's Cap", "clerics_cap", "whm", "WHM Head"}},
    {15136, {"Duelist's Boots", "duelists_boots", "rdm", "RDM Feet"}},
    {15108, {"Valor Gauntlets", "valor_gauntlets", "pld", "PLD Hands"}},
    {15125, {"Monster Trousers", "monster_trousers", "bst", "BST Legs"}},
    {15081, {"Bard's Roundlet", "bards_roundlet", "brd", "BRD Head"}},
    {15127, {"Scout's Braccae", "scouts_braccae", "rng", "RNG Legs"}},
    {15129, {"Koga Hakama", "koga_hakama", "nin", "NIN Legs"}},
    {15145, {"Wyrm Greaves", "wyrm_greaves", "drg", "DRG Feet"}},
    {15146, {"Summoner's Pigaches", "summoners_pigaches", "smn", "SMN Feet"}},
    {15025, {"Mirage Bazubands", "mirage_bazubands", "blu", "BLU Hands"}},
    {16349, {"Commodore Trews", "commodore_trews", "cor", "COR Legs"}},
    {11388, {"Pantin Babouches", "pantin_babouches", "pup", "PUP Feet"}},
    {15133, {"Melee Gaiters", "melee_gaiters", "mnk", "MNK Feet"}},
    {15120, {"Sorcerer's Tonban", "sorcerers_tonban", "blm", "BLM Legs"}},
    {15106, {"Duelist's Gloves", "duelists_gloves", "rdm", "RDM Hands"}},
    {15092, {"Assassin's Vest", "assassins_vest", "thf", "THF Body"}},
    {15078, {"Valor Coronet", "valor_coronet", "pld", "PLD Head"}},
    {15139, {"Abyss Sollerets", "abyss_sollerets", "drk", "DRK Feet"}},
    {15095, {"Monster Jackcoat", "monster_jackcoat", "bst", "BST Body"}},
    {15111, {"Bard's Cuffs", "bards_cuffs", "brd", "BRD Hands"}},
    {15113, {"Saotome Kote", "saotome_kote", "sam", "SAM Hands"}},
    {15130, {"Wyrm Brais", "wyrm_brais", "drg", "DRG Legs"}},
    {15116, {"Summoner's Bracers", "summoners_bracers", "smn", "SMN Hands"}},
    {16346, {"Mirage Shalwar", "mirage_shalwar", "blu", "BLU Legs"}},
    {11385, {"Commodore Bottes", "commodore_bottes", "cor", "COR Feet"}},
    {11478, {"Etoile Tiara", "etoile_tiara", "dnc", "DNC Head"}},
    {16362, {"Argute Pants", "argute_pants_", "sch", "SCH Legs"}},
    {15072, {"Warrior's Mask", "warriors_mask", "war", "WAR Head"}},
    {15134, {"Cleric's Duckbills", "clerics_duckbills", "whm", "WHM Feet"}},
    {15105, {"Sorcerer's Gloves", "sorcerers_gloves", "blm", "BLM Hands"}},
    {15077, {"Assassin's Bonnet", "assassins_bonnet", "thf", "THF Head"}},
    {15138, {"Valor Leggings", "valor_leggings", "pld", "PLD Feet"}},
    {15109, {"Abyss Gauntlets", "abyss_gauntlets", "drk", "DRK Hands"}},
    {15080, {"Monster Helm", "monster_helm", "bst", "BST Head"}},
    {15112, {"Scout's Bracers", "scouts_bracers", "rng", "RNG Hands"}},
    {15128, {"Saotome Haidate", "saotome_haidate", "sam", "SAM Legs"}},
    {15084, {"Koga Hatsuburi", "koga_hatsuburi", "nin", "NIN Head"}},
    {15131, {"Summoner's Spats", "summoners_spats", "smn", "SMN Legs"}},
    {11382, {"Mirage Charuqs", "mirage_charuqs", "blu", "BLU Feet"}},
    {15031, {"Pantin Dastanas", "pantin_dastanas", "pup", "PUP Hands"}},
    {15038, {"Etoile Bangles", "etoile_bangles", "dnc", "DNC Hands"}},
    {11398, {"Argute Loafers", "argute_loafers", "sch", "SCH Feet"}},
    {15102, {"Warrior's Mufflers", "warriors_mufflers", "war", "WAR Hands"}},
    {15103, {"Melee Gloves", "melee_gloves", "mnk", "MNK Hands"}},
    {15119, {"Cleric's Pantaloons", "clerics_pantaloons", "whm", "WHM Legs"}},
    {15135, {"Sorcerer's Sabots", "sorcerers_sabots", "blm", "BLM Feet"}},
    {15121, {"Duelist's Tights", "duelists_tights", "rdm", "RDM Legs"}},
    {15137, {"Assassin's Poulaines", "assassins_poulaines", "thf", "THF Feet"}},
    {15124, {"Abyss Flanchard", "abyss_flanchard", "drk", "DRK Legs"}},
    {15141, {"Bard's Slippers", "bards_slippers", "brd", "BRD Feet"}},
    {15082, {"Scout's Beret", "scouts_beret", "rng", "RNG Head"}},
    {15143, {"Saotome Sune-Ate", "saotome_sune-ate", "sam", "SAM Feet"}},
    {15144, {"Koga Kyahan", "koga_kyahan", "nin", "NIN Feet"}},
    {15115, {"Wyrm Finger Gauntlets", "wyrm_finger_gauntlets", "drg", "DRG Hands"}},
    {15028, {"Commodore Gants", "commodore_gants", "cor", "COR Hands"}},
    {16352, {"Pantin Churidars", "pantin_churidars", "pup", "PUP Legs"}},
    {11396, {"Etoile Shoes", "etoile_shoes", "dnc", "DNC Feet"}},
    {15117, {"Warrior's Cuisses", "warriors_cuisses", "war", "WAR Legs"}},
    {15088, {"Melee Cyclas", "melee_cyclas", "mnk", "MNK Body"}},
    {15089, {"Cleric's Bliault", "clerics_bliault", "whm", "WHM Body"}},
    {15090, {"Sorcerer's Coat", "sorcerers_coat", "blm", "BLM Body"}},
    {15091, {"Duelist's Tabard", "duelists_tabard", "rdm", "RDM Body"}},
    {15122, {"Assassin's Culottes", "assassins_culottes", "thf", "THF Legs"}},
    {15123, {"Valor Breeches", "valor_breeches", "pld", "PLD Legs"}},
    {15094, {"Abyss Cuirass", "abyss_cuirass", "drk", "DRK Body"}},
    {15140, {"Monster Gaiters", "monster_gaiters", "bst", "BST Feet"}},
    {15096, {"Bard's Justaucorps", "bards_justaucorps", "brd", "BRD Body"}},
    {15142, {"Scout's Socks", "scouts_socks", "rng", "RNG Feet"}},
    {15098, {"Saotome Domaru", "saotome_domaru", "sam", "SAM Body"}},
    {15099, {"Koga Chainmail", "koga_chainmail", "nin", "NIN Body"}},
    {15100, {"Wyrm Mail", "wyrm_mail", "drg", "DRG Body"}},
    {15101, {"Summoner's Doublet", "summoners_doublet", "smn", "SMN Body"}},
    {11292, {"Mirage Jubbah", "mirage_jubbah", "blu", "BLU Body"}},
    {11295, {"Commodore Frac", "commodore_frac", "cor", "COR Body"}},
    {11298, {"Pantin Tobe", "pantin_tobe", "pup", "PUP Body"}},
    {16360, {"Etoile Tights", "etoile_tights", "dnc", "DNC Legs"}},
    {11307, {"Argute Gown", "argute_gown", "sch", "SCH Body"}},
    {15087, {"Warrior's Lorica", "warriors_lorica", "war", "WAR Body"}},
    {15073, {"Melee Crown", "melee_crown", "mnk", "MNK Head"}},
    {15104, {"Cleric's Mitts", "clerics_mitts", "whm", "WHM Hands"}},
    {15075, {"Sorcerer's Petasos", "sorcerers_petasos", "blm", "BLM Head"}},
    {15076, {"Duelist's Chapeau", "duelists_chapeau", "rdm", "RDM Head"}},
    {15107, {"Assassin's Armlets", "assassins_armlets", "thf", "THF Hands"}},
    {15093, {"Valor Surcoat", "valor_surcoat", "pld", "PLD Body"}},
    {15079, {"Abyss Burgeonet", "abyss_burgeonet", "drk", "DRK Head"}},
    {15110, {"Monster Gloves", "monster_gloves", "bst", "BST Hands"}},
    {15126, {"Bard's Cannions", "bards_cannions", "brd", "BRD Legs"}},
    {15097, {"Scout's Jerkin", "scouts_jerkin", "rng", "RNG Body"}},
    {15083, {"Saotome Kabuto", "saotome_kabuto", "sam", "SAM Head"}},
    {15114, {"Koga Tekko", "koga_tekko", "nin", "NIN Hands"}},
    {15085, {"Wyrm Armet", "wyrm_armet", "drg", "DRG Head"}},
    {15086, {"Summoner's Horn", "summoners_horn", "smn", "SMN Head"}},
    {11465, {"Mirage Keffiyeh", "mirage_keffiyeh", "blu", "BLU Head"}},
    {11468, {"Commodore Tricorne", "commodore_tricorne", "cor", "COR Head"}},
    {11471, {"Pantin Taj", "pantin_taj", "pup", "PUP Head"}},
    {11305, {"Etoile Casaque", "etoile_casaque", "dnc", "DNC Body"}},
    {11480, {"Argute Mortarboard", "argute_m.board", "sch", "SCH Head"}},
    {2068, {"Abyss Burgeonet -1", "abyss_burgeonet_-1", "drk-up", "DRK head-1"}},
    {15479, {"Abyss Cape", "abyss_cape", "drk-acc", "DRK acc"}},
    {2069, {"Abyss Cuirass -1", "abyss_cuirass_-1", "drk-up", "DRK body-1"}},
    {2071, {"Abyss Flanchard -1", "abyss_flanchard_-1", "drk-up", "DRK legs-1"}},
    {2070, {"Abyss Gauntlets -1", "abyss_gauntlets_-1", "drk-up", "DRK hands-1"}},
    {2072, {"Abyss Sollerets -1", "abyss_sollerets_-1", "drk-up", "DRK feet-1"}},
    {15925, {"Argute Belt", "argute_belt", "sch-acc", "SCH acc"}},
    {2725, {"Argute Bracers -1", "argute_bracers_-1", "sch-up", "SCH hands-1"}},
    {2724, {"Argute Gown -1", "argute_gown_-1", "sch-up", "SCH body-1"}},
    {2727, {"Argute Loafers -1", "argute_loafers_-1", "sch-up", "SCH feet-1"}},
    {2723, {"Argute Mortarboard -1", "argute_mortarboard_-1", "sch-up", "SCH head-1"}},
    {2726, {"Argute Pants -1", "argute_pants_-1", "sch-up", "SCH legs-1"}},
    {2060, {"Assassin's Armlets -1", "assassins_armlets_-1", "thf-up", "THF hands-1"}},
    {2058, {"Assassin's Bonnet -1", "assassins_bonnet_-1", "thf-up", "THF head-1"}},
    {15480, {"Assassin's Cape", "assassins_cape", "thf-acc", "THF acc"}},
    {2061, {"Assassin's Culotte -1", "assassins_culotte_-1", "thf-up", "THF legs-1"}},
    {2062, {"Assassin's Poulaines -1", "assassins_poulaines_-1", "thf-up", "THF feet-1"}},
    {2059, {"Assassin's Vest -1", "assassins_vest_-1", "thf-up", "THF body-1"}},
    {2081, {"Bard's Cannions -1", "bards_cannions_-1", "brd-up", "BRD legs-1"}},
    {15482, {"Bard's Cape", "bards_cape", "brd-acc", "BRD acc"}},
    {2080, {"Bard's Cuffs -1", "bards_cuffs_-1", "brd-up", "BRD hands-1"}},
    {2079, {"Bard's Justaucorps -1", "bards_justaucorps_-1", "brd-up", "BRD body-1"}},
    {2078, {"Bard's Roundlet -1", "bards_roundlet_-1", "brd-up", "BRD head-1"}},
    {2082, {"Bard's Slippers -1", "bards_slippers_-1", "brd-up", "BRD feet-1"}},
    {15872, {"Cleric's Belt", "clerics_belt", "whm-acc", "WHM acc"}},
    {2044, {"Cleric's Briault -1", "clerics_briault_-1", "whm-up", "WHM body-1"}},
    {2043, {"Cleric's Cap -1", "clerics_cap_-1", "whm-up", "WHM head-1"}},
    {2047, {"Cleric's Duckbills -1", "clerics_duckbills_-1", "whm-up", "WHM feet-1"}},
    {2045, {"Cleric's Mitts -1", "clerics_mitts_-1", "whm-up", "WHM hands-1"}},
    {2046, {"Cleric's Pantaloons -1", "clerics_pantaloons_-1", "whm-up", "WHM legs-1"}},
    {15920, {"Commodore Belt", "commodore_belt", "cor-acc", "COR acc"}},
    {2671, {"Commodore Bottes -1", "commodore_bottes_-1", "cor-up", "COR feet-1"}},
    {2668, {"Commodore Frac -1", "commodore_frac_-1", "cor-up", "COR body-1"}},
    {2669, {"Commodore Gants -1", "commodore_gants_-1", "cor-up", "COR hands-1"}},
    {2670, {"Commodore Trews -1", "commodore_trews_-1", "cor-up", "COR legs-1"}},
    {2667, {"Commodore Tricorne -1", "commodore_tricorne_-1", "cor-up", "COR head-1"}},
    {15873, {"Duelist's Belt", "duelists_belt", "rdm-acc", "RDM acc"}},
    {2057, {"Duelist's Boots -1", "duelists_boots_-1", "rdm-up", "RDM feet-1"}},
    {2053, {"Duelist's Chapeau -1", "duelists_chapeau_-1", "rdm-up", "RDM head-1"}},
    {2055, {"Duelist's Gloves -1", "duelists_gloves_-1", "rdm-up", "RDM hands-1"}},
    {2054, {"Duelist's Tabard -1", "duelists_tabard_-1", "rdm-up", "RDM body-1"}},
    {2056, {"Duelist's Tights -1", "duelists_tights_-1", "rdm-up", "RDM legs-1"}},
    {2720, {"Etoile Bangles -1", "etoile_bangles_-1", "dnc-up", "DNC hads-1"}},
    {16248, {"Etoile Cape", "etoile_cape", "dnc-acc", "DNC acc"}},
    {2719, {"Etoile Casaque -1", "etoile_casaque_-1", "dnc-up", "DNC body-1"}},
    {2718, {"Etoile Tiara -1", "etoile_tiara_-1", "dnc-up", "DNC head-1"}},
    {2721, {"Etoile Tights -1", "etoile_tights_-1", "dnc-up", "DNC legs-1"}},
    {2722, {"Etoile Toe Shoes -1", "etoile_toe_shoes_-1", "dnc-up", "DNC feet-1"}},
    {2094, {"Koga Chainmail -1", "koga_chainmail_-1", "nin-up", "NIN body-1"}},
    {2096, {"Koga Hakama -1", "koga_hakama_-1", "nin-up", "NIN legs-1"}},
    {2093, {"Koga Hatsuburi -1", "koga_hatsuburi_-1", "nin-up", "NIN head-1"}},
    {2097, {"Koga Kyahan -1", "koga_kyahan_-1", "nin-up", "NIN feet-1"}},
    {15877, {"Koga Sarashi", "koga_sarashi", "nin-acc", "NIN acc"}},
    {2095, {"Koga Tekko -1", "koga_tekko_-1", "nin-up", "NIN hands-1"}},
    {15478, {"Melee Cape", "melee_cape", "mnk-acc", "MNK acc"}},
    {2038, {"Melee Crown -1", "melee_crown_-1", "mnk-up", "MNK head-1"}},
    {2039, {"Melee Cyclas -1", "melee_cyclas_-1", "mnk-up", "MNK body-1"}},
    {2042, {"Melee Gaiters -1", "melee_gaiters_-1", "mnk-up", "MNK feet-1"}},
    {2040, {"Melee Gloves -1", "melee_gloves_-1", "mnk-up", "MNK hands-1"}},
    {2041, {"Melee Hose -1", "melee_hose_-1", "mnk-up", "MNK legs-1"}},
    {2664, {"Mirage Bazubands -1", "mirage_bazubands_-1", "blu-up", "BLU hands-1"}},
    {2666, {"Mirage Charuqs -1", "mirage_charuqs_-1", "blu-up", "BLU feet-1"}},
    {2663, {"Mirage Jubbah -1", "mirage_jubbah_-1", "blu-up", "BLU body-1"}},
    {2662, {"Mirage Keffiyeh -1", "mirage_keffiyeh_-1", "blu-up", "BLU head-1"}},
    {16244, {"Mirage Mantle", "mirage_mantle", "blu-acc", "BLU acc"}},
    {2665, {"Mirage Shalwar -1", "mirage_shalwar_-1", "blu-up", "BLU legs-1"}},
    {15875, {"Monster Belt", "monster_belt", "bst-acc", "BST acc"}},
    {2077, {"Monster Gaiters -1", "monster_gaiters_-1", "bst-up", "BST feet-1"}},
    {2075, {"Monster Gloves -1", "monster_gloves_-1", "bst-up", "BST hands-1"}},
    {2073, {"Monster Helm -1", "monster_helm_-1", "bst-up", "BST head-1"}},
    {2074, {"Monster Jackcoat -1", "monster_jackcoat_-1", "bst-up", "BST body-1"}},
    {2076, {"Monster Trousers -1", "monster_trousers_-1", "bst-up", "BST legs-1"}},
    {2676, {"Pantin Babouches -1", "pantin_babouches_-1", "pup-up", "PUP feet-1"}},
    {16245, {"Pantin Cape", "pantin_cape", "pup-acc", "PUP acc"}},
    {2675, {"Pantin Churidars -1", "pantin_churidars_-1", "pup-up", "PUP legs-1"}},
    {2674, {"Pantin Dastanas -1", "pantin_dastanas_-1", "pup-up", "PUP hands-1"}},
    {2672, {"Pantin Taj -1", "pantin_taj_-1", "pup-up", "PUP head-1"}},
    {2673, {"Pantin Tobe -1", "pantin_tobe_-1", "pup-up", "PUP body-1"}},
    {2089, {"Saotome Domaru -1", "saotome_domaru_-1", "sam-up", "SAM body-1"}},
    {2091, {"Saotome Haidate -1", "saotome_haidate_-1", "sam-up", "SAM legs-1"}},
    {2088, {"Saotome Kabuto -1", "saotome_kabuto_-1", "sam-up", "SAM head-1"}},
    {15879, {"Saotome Koshi-Ate", "saotome_koshi-ate", "sam-acc", "SAM acc"}},
    {2090, {"Saotome Kote -1", "saotome_kote_-1", "sam-up", "SAM hands-1"}},
    {2092, {"Saotome Sune-Ate -1", "saotome_sune-ate_-1", "sam-up", "SAM feet-1"}},
    {15876, {"Scout's Belt", "scouts_belt", "rng-acc", "RNG acc"}},
    {2083, {"Scout's Beret -1", "scouts_beret_-1", "rng-up", "RNG head-1"}},
    {2086, {"Scout's Braccae -1", "scouts_braccae_-1", "rng-up", "RNG legs-1"}},
    {2085, {"Scout's Bracers -1", "scouts_bracers_-1", "rng-up", "RNG hands-1"}},
    {2084, {"Scout's Jerkin -1", "scouts_jerkin_-1", "rng-up", "RNG body-1"}},
    {2087, {"Scout's Socks -1", "scouts_socks_-1", "rng-up", "RNG feet-1"}},
    {15874, {"Sorcerer's Belt", "sorcerers_belt", "blm-acc", "BLM acc"}},
    {2049, {"Sorcerer's Coat -1", "sorcerers_coat_-1", "blm-up", "BLM body-1"}},
    {2050, {"Sorcerer's Gloves -1", "sorcerers_gloves_-1", "blm-up", "BLM hands-1"}},
    {2048, {"Sorcerer's Petasos -1", "sorcerers_petasos_-1", "blm-up", "BLM head-1"}},
    {2052, {"Sorcerer's Sabots -1", "sorcerers_sabots_-1", "blm-up", "BLM feet-1"}},
    {2051, {"Sorcerer's Tonban -1", "sorcerers_tonban_-1", "blm-up", "BLM legs-1"}},
    {2105, {"Summoner's Bracers -1", "summoners_bracers_-1", "smn-up", "SMN hands-1"}},
    {15484, {"Summoner's Cape", "summoners_cape", "smn-acc", "SMN acc"}},
    {2104, {"Summoner's Doublet -1", "summoners_doublet_-1", "smn-up", "SMN body-1"}},
    {2103, {"Summoner's Horn -1", "summoners_horn_-1", "smn-up", "SMN head-1"}},
    {2107, {"Summoner's Pigaches -1", "summoners_pigaches_-1", "smn-up", "SMN feet-1"}},
    {2106, {"Summoner's Spats -1", "summoners_spats_-1", "smn-up", "SMN legs-1"}},
    {2066, {"Valor Breeches -1", "valor_breeches_-1", "pld-up", "PLD legs-1"}},
    {15481, {"Valor Cape", "valor_cape", "pld-acc", "PLD acc"}},
    {2063, {"Valor Coronet -1", "valor_coronet_-1", "pld-up", "PLD head-1"}},
    {2065, {"Valor Gauntlets -1", "valor_gauntlets_-1", "pld-up", "PLD hands-1"}},
    {2067, {"Valor Leggings -1", "valor_leggings_-1", "pld-up", "PLD feet-1"}},
    {2064, {"Valor Surcoat -1", "valor_surcoat_-1", "pld-up", "PLD body-1"}},
    {2037, {"Warrior's Calligae -1", "warriors_calligae_-1", "war-up", "WAR feet-1"}},
    {2036, {"Warrior's Cuisses -1", "warriors_cuisses_-1", "war-up", "WAR legs-1"}},
    {2034, {"Warrior's Lorica -1", "warriors_lorica_-1", "war-up", "WAR body-1"}},
    {2033, {"Warrior's Mask -1", "warriors_mask_-1", "war-up", "WAR head-1"}},
    {2035, {"Warrior's Mufflers -1", "warriors_mufflers_-1", "war-up", "WAR hands-1"}},
    {15871, {"Warrior's Stone", "warriors_stone", "war-acc", "WAR acc"}},
    {2098, {"Wyrm Armet -1", "wyrm_armet_-1", "drg-up", "DRG head-1"}},
    {15878, {"Wyrm Belt", "wyrm_belt", "drg-acc", "DRG acc"}},
    {2101, {"Wyrm Brais -1", "wyrm_brais_-1", "drg-up", "DRG legs-1"}},
    {2100, {"Wyrm Finger Gauntlets -1", "wyrm_finger_gauntlets_-1", "drg-up", "DRG hands-1"}},
    {2102, {"Wyrm Greaves -1", "wyrm_greaves_-1", "drg-up", "DRG feet-1"}},
    {2099, {"Wyrm Mail -1", "wyrm_mail_-1", "drg-up", "DRG body-1"}},

    { 1324, {"Aquarian Abjuration: Head", "Aquarian_Abjuration:_Head", "zen-head", "A Head"} },
    { 1325, {"Aquarian Abjuration: Body", "Aquarian_Abjuration:_Body", "zen-body", "A Body"} },
    { 1326, {"Aquarian Abjuration: Hands", "Aquarian_Abjuration:_Hands", "zen-hands", "A Hands"} },
    { 1327, {"Aquarian Abjuration: Legs", "Aquarian_Abjuration:_Legs", "zen-legs", "A Legs"} },
    { 1328, {"Aquarian Abjuration: Feet", "Aquarian_Abjuration:_Feet", "zen-feet", "A Feet"} },
    { 1314, {"Dryadic Abjuration: Head", "Dryadic_Abjuration:_Head", "shura-head", "D Head"} },
    { 1315, {"Dryadic Abjuration: Body", "Dryadic_Abjuration:_Body", "shura-body", "D Body"} },
    { 1316, {"Dryadic Abjuration: Hands", "Dryadic_Abjuration:_Hands", "shura-hands", "D Hands"} },
    { 1317, {"Dryadic Abjuration: Legs", "Dryadic_Abjuration:_Legs", "shura-legs", "D Legs"} },
    { 1318, {"Dryadic Abjuration: Feet", "Dryadic_Abjuration:_Feet", "shura-feet", "D Feet"} },
    { 1319, {"Earthen Abjuration: Head", "Earthen_Abjuration:_Head", "earth-head", "E Head"} },
    { 1320, {"Earthen Abjuration: Body", "Earthen_Abjuration:_Body", "earth-body", "E Body"} },
    { 1321, {"Earthen Abjuration: Hands", "Earthen_Abjuration:_Hands", "earth-hands", "E Hands"} },
    { 1322, {"Earthen Abjuration: Legs", "Earthen_Abjuration:_Legs", "earth-legs", "E Legs"} },
    { 1323, {"Earthen Abjuration: Feet", "Earthen_Abjuration:_Feet", "earth-feet", "E Feet"} },
    { 1339, {"Neptunal Abjuration: Head", "Neptunal_Abjuration:_Head", "heca-head", "N Head"} },
    { 1340, {"Neptunal Abjuration: Body", "Neptunal_Abjuration:_Body", "heca-body", "N Body"} },
    { 1341, {"Neptunal Abjuration: Hands", "Neptunal_Abjuration:_Hands", "heca-hands", "N Hands"} },
    { 1342, {"Neptunal Abjuration: Legs", "Neptunal_Abjuration:_Legs", "heca-legs", "N Legs"} },
    { 1343, {"Neptunal Abjuration: Feet", "Neptunal_Abjuration:_Feet", "heca-feet", "N Feet"} },
    { 1329, {"Martial Abjuration: Head", "Martial_Abjuration:_Head", "koen-head", "M Head"} },
    { 1330, {"Martial Abjuration: Body", "Martial_Abjuration:_Body", "koen-body", "M Body"} },
    { 1331, {"Martial Abjuration: Hands", "Martial_Abjuration:_Hands", "koen-hands", "M Hands"} },
    { 1332, {"Martial Abjuration: Legs", "Martial_Abjuration:_Legs", "koen-legs", "M Legs"} },
    { 1333, {"Martial Abjuration: Feet", "Martial_Abjuration:_Feet", "koen-feet", "M Feet"} },
    { 1334, {"Wyrmal Abjuration: Head", "Wyrmal_Abjuration:_Head", "crim-head", "W Head"} },
    { 1335, {"Wyrmal Abjuration: Body", "Wyrmal_Abjuration:_Body", "crim-body", "W Body"} },
    { 1336, {"Wyrmal Abjuration: Hands", "Wyrmal_Abjuration:_Hands", "crim-hands", "W Hands"} },
    { 1337, {"Wyrmal Abjuration: Legs", "Wyrmal_Abjuration:_Legs", "crim-legs", "W Legs"} },
    { 1338, {"Wyrmal Abjuration: Feet", "Wyrmal_Abjuration:_Feet", "crim-feet", "W Feet"} },
    { 15260, {"Hydra Beret", "Hydra_Beret", "hyd-bere", "Hydra Beret"} },
    { 14515, {"Hydra Doublet", "Hydra_Doublet", "hyd-doub", "Hydra Doublet"} },
    { 14924, {"Hydra Gloves", "Hydra_Gloves", "hyd-glov", "Hydra Gloves"} },
    { 15595, {"Hydra Brais", "Hydra_Brais", "hyd-brais", "Hydra Brais"} },
    { 15680, {"Hydra Gaiters", "Hydra_Gaiters", "hyd-gait", "Hydra Gaiters"} },
    { 15261, {"Hydra Tiara", "Hydra_Tiara", "hyd-tia", "Hydra Tiara"} },
    { 14516, {"Hydra Harness", "Hydra_Harness", "hyd-harn", "Hydra Harness"} },
    { 14925, {"Hydra Mittens", "Hydra_Mittens", "hyd-mitt", "Hydra Mittens"} },
    { 15596, {"Hydra Tights", "Hydra_Tights", "hyd-tigh", "Hydra Tights"} },
    { 15681, {"Hydra Spats", "Hydra_Spats", "hyd-spat", "Hydra Spats"} },
    { 15262, {"Hydra Salade", "Hydra_Salade", "hyd-sala", "Hydra Salade"} },
    { 14517, {"Hydra Haubert", "Hydra_Haubert", "hyd-haub", "Hydra Haubert"} },
    { 14926, {"Hydra Moufles", "Hydra_Moufles", "hyd-mouf", "Hydra Moufles"} },
    { 15597, {"Hydra Brayetees", "Hydra_Brayetees", "hyd-bray", "Hydra Brayetees"} },
    { 15682, {"Hydra Sollerets", "Hydra_Sollerets", "hyd-soll", "Hydra Sollerets"} },
    { 15263, {"Hydra Cap", "Hydra_Cap", "hyd-cap", "Hydra Cap"} },
    { 14518, {"Hydra Jupon", "Hydra_Jupon", "hyd-jup", "Hydra Jupon"} },
    { 14927, {"Hydra Bracers", "Hydra_Bracers", "hyd-brac", "Hydra Bracers"} },
    { 15598, {"Hydra Hose", "Hydra_Hose", "hyd-hose", "Hydra Hose"} },
    { 15683, {"Hydra Boots", "Hydra_Boots", "hyd-boots", "Hydra Boots"} },
    { 18198, {"Byakko's Axe", "Byakko's_Axe", "byak-axe", "Byakko Axe"} },
    { 12818, {"Byakko's Haidate", "Byakko's_Haidate", "byak-haid", "Haidate"} },
    { 12434, {"Genbu's Kabuto", "Genbu's_Kabuto", "gen-kab", "Genbu kabuto"} },
    { 12296, {"Genbu's Shield", "Genbu's_Shield", "gen-shield", "Genbu shield"} },
    { 12690, {"Seiryu's Kote", "Seiryu's_Kote", "seir-kote", "Seiryu Kote"} },
    { 17659, {"Seiryu's Sword", "Seiryu's_Sword", "seir-sword", "Seiryu Sword"} },
    { 18043, {"Suzaku's Scythe", "Suzaku's Scythe", "suz-scy", "Suzy Scythe"} },
    { 12946, {"Suzaku's Sune-Ate", "Suzaku's_Sune-Ate", "suz-feet", "Suzy feet"} },
    { 12562, {"Kirin's Osode", "Kirin's_Osode", "kirin-osode", "Kirin osode"} },
    { 17567, {"Kirin's Pole", "Kirin's_Pole", "kirin-pole", "Kirin pole"} },
    { 13914, {"Aegishjalmr", "Aegishjalmr", "aegi", "Assjammer"} },
    { 16942, {"Balmung", "Balmung", "balmung", "Balmong"} },
    { 17653, {"Hrotti", "Hrotti", "hrotti", "Hrotti"} },
    { 16555, {"Ridill", "Ridill", "ridill", "Ridill"} },
    { 1526, {"Wyrm Beard", "Wyrm_Beard", "wyrm-beard", "Wyrm Beard"} },
    { 13566, {"Defending Ring", "Defending_Ring", "def-ring", "DRING"} },
    { 13415, {"Pixie Earring", "Pixie_Earring", "pix-ear", "Pixie Earring"} },
    { 1527, {"Behemoth Tongue", "Behemoth_Tongue", "behe-tong", "Behe tongue"} },
    { 1525, {"Adamantoise Egg", "Adamantoise_Egg", "adam-egg", "EGG"} },
    { 15899, {"Velocious Belt", "Velocious_Belt", "velo-belt", "V Belt"} },
    { 17598, {"Bahamut's Staff", "Bahamut's_Staff", "baha-staff", "Bahamut staff"} },
    { 17597, {"Dragon Staff", "Dragon_Staff", "drag-staff", "Dorgon staff"} },
    { 15264, {"Bahamut's Mask", "Bahamut's_Mask", "baha-mask", "Bahamut Mask"} },
    { 18061, {"Bahamut's Zaghnal", "Bahamut's_Zaghnal", "baha-zag", "Bahamat Zaghnal"} },
    { 15599, {"Bahamut's Hose", "Bahamut's_Hose", "baha-hose", "Bahamot Hose"} },
    { 17595, {"Hope Staff", "Hope_Staff", "hope-staff", "Hope Staff"} },
    { 15509, {"Hope Torque", "Hope_Torque", "hope-tor", "Hope Torque"} },
    { 17710, {"Justice Sword", "Justice_Sword", "just-sword", "Justice Sword"} },
    { 15508, {"Justice Torque", "Justice_Torque", "just-tor", "Justice Torque"} },
    { 18397, {"Prudence Rod", "Prudence_Rod", "prud-rod", "Prudence Rod"} },
    { 15510, {"Prudence Torque", "Prudence_Torque", "prud-tor", "Prudence Torque"} },
    { 18100, {"Love Halberd", "Love_Halberd", "love-hal", "Love Halberd"} },
    { 15514, {"Love Torque", "Love_Torque", "love-tor", "Love Torque"} },
    { 1911, {"Aura of Adulation", "Aura_of_Adulation", "novio", "NOVIO"} },
    { 1912, {"Aura of Voracity", "Aura_of_Voracity", "novia", "NOVIA"} },
    { 1902, {"Vice of Avarice", "Vice_of_Avarice", "altr-cape", "Altruism Cape"} },
    { 1903, {"Vice of Aspersion", "Vice_of_Aspersion", "ast-cape", "Astute Cape"} },
    { 1901, {"Vice of Antipathy", "Vice_of_Antipathy", "merc-cape", "Merciful Cape"} },
    { 17948, {"Temperance Axe", "Temperance_Axe", "temp-axe", "Temp Axe"} },
    { 15513, {"Temperance Torque", "Temperance_Torque", "temp-tor", "Temp Torque"} },
    { 18360, {"Faith Baghnakhs", "Faith_Baghnakhs", "faith-h2h", "Faith h2h"} },
    { 15512, {"Faith Torque", "Faith_Torque", "faith-tor", "Faith Torque"} },
    { 18222, {"Fortitude Axe", "Fortitude_Axe", "fort-axe", "Fort. Axe"} },
    { 15511, {"Fortitude Torque", "Fortitude_Torque", "fort-tor", "Fort. Torque"} },
    { 16155, {"Aurum Armet", "Aurum_Armet", "aur-arm", "Aurum Head"} },
    { 11282, {"Aurum Cuirass", "Aurum_Cuirass", "aur-cuir", "Aurum Body"} },
    { 15021, {"Aurum Gauntlets", "Aurum_Gauntlets", "aur-gaun", "Aurum Hands"} },
    { 16341, {"Aurum Cuisses", "Aurum_Cuisses", "aur-cuis", "Aurum Legs"} },
    { 11376, {"Aurum Sabatons", "Aurum_Sabatons", "aur-saba", "Aurum Feet"} },
    { 16156, {"Oracle's Cap", "Oracle's_Cap", "ora-cap", "Oracle Head"} },
    { 11283, {"Oracle's Robe", "Oracle's_Robe", "ora-robe", "Oracle Body"} },
    { 15022, {"Oracle's Gloves", "Oracle's_Gloves", "ora-glov", "Oracle Hands"} },
    { 16342, {"Oracle's Braconi", "Oracle's_Braconi", "ora-brac", "Oracle Legs"} },
    { 11377, {"Oracle's Pigaches", "Oracle's_Pigaches", "ora-piga", "Oracle Feet"} },
    { 16157, {"Enkidu's Cap", "Enkidu's_Cap", "enk-cap", "Enkidu Head"} },
    { 11284, {"Enkidu's Harness", "Enkidu's_Harness", "enk-harn", "Enkidu Body"} },
    { 15023, {"Enkidu's Mittens", "Enkidu's_Mittens", "enk-mitt", "Enkidu Hands"} },
    { 16343, {"Enkidu's Subligar", "Enkidu's_Subligar", "enk-sub", "Enkidu Legs"} },
    { 11378, {"Enkidu's Leggings", "Enkidu's_Leggings", "enk-leg", "Enkidu Feet"} },
    { 11281, {"Hachiryu Haramaki", "Hachiryu_Haramaki", "hac-hara", "Hachiryu Head"} },
    { 15015, {"Hachiryu Kote", "Hachiryu_Kote", "hac-kote", "Hachiryu Body"} },
    { 16337, {"Hachiryu Haidate", "Hachiryu_Haidate", "hac-haid", "Hachiryu Legs"} },
    { 11364, {"Hachiryu Sune-Ate", "Hachiryu_Sune-Ate", "hac-sune", "Hachiryu Feet"} },
    { 19038, {"Dark Grip", "Dark_Grip", "d-grip", "Dark Grip"} },
    { 19036, {"Earth Grip", "Earth_Grip", "e-grip", "Earth Grip"} },
    { 19031, {"Fire Grip", "Fire_Grip", "f-grip", "Fire Grip"} },
    { 19034, {"Ice Grip", "Ice_Grip", "i-grip", "Ice Grip"} },
    { 19037, {"Light Grip", "Light_Grip", "l-grip", "Light Grip"} },
    { 19035, {"Thunder Grip", "Thunder_Grip", "t-grip", "Thunder Grip"} },
    { 19032, {"Water Grip", "Water_Grip", "water-grip", "Water Grip"} },
    { 19033, {"Wind Grip", "Wind_Grip", "wind-grip", "Wind Grip"} },
    { 18126, {"Tomoe", "Tomoe", "tomoe", "Tomoe"} },
    { 19153, {"Naglering", "Naglering", "nagl", "Naglering"} },
    { 18125, {"Cletine", "Cletine", "clet", "Cletine"} },
    { 17753, {"Organics", "Organics", "organ", "Organics"} },
    { 16176, {"Simba Buckler", "Simba_Buckler", "sim-buck", "Simba Buckler"} },
    { 17960, {"Labrys", "Labrys", "labrys", "Labrys"} },
    { 18595, {"Mekki Shakki", "Mekki_Shakki", "mek-shak", "Mekki Shakki"} },
    { 16177, {"Legion Scutum", "Legion_Scutum", "leg-scut", "Legion Scrotum"} },
    { 18430, {"Oninohocho", "Oninohocho", "onin", "Oninohocho"} },
    { 18593, {"Alkalurops", "Alkalurops", "alka", "Akrapulops"} },
    { 18429, {"Shusui", "Shusui", "shus", "Sushi"} },
    { 18497, {"Foolkiller", "Foolkiller", "fool", "Footkiller"} },
    { 18446, {"Pachipachio", "Pachipachio", "pach", "PeachyPachio"} },
    { 18857, {"Antares", "Antares", "antar", "Antardes"} },
    { 18948, {"Enforcer", "Enforcer", "enfor", "Enbargo"} },
    { 17738, {"Hauteclaire", "Hauteclaire", "haute", "Hottyclaire"} },
    { 18847, {"Seveneyes", "Seveneyes", "seven", "Foureyes"} },
    { 18385, {"Algol", "Algol", "algol", "Goolgol"} },
    { 13658, {"Shadow Mantle", "Shadow Mantle", "shad-man", "Spicy Mantle"}},
    { 14646, {"Shadow Ring", "Shadow Ring", "shad-ring", "Spicy Ring"}},


    {841,{"Yagudo Feather", "yagudo_feather", "yag", "YAG"}},
    { 4108, {"Lightning Cluster", "lightning_cluster", "lig", "LIG"}},
    { 856, {"Rabbit Hide", "rabbit_hide", "rab", "RAB"}},
    {505, {"Sheepskin", "sheepskin", "shp", "SHP"}},
    {4372, {"G.Sheep Meat", "g_sheep_meat", "meat", "MEAT"}},
};